### ISSUE TITLE
Constant load optimization

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#1096]
Any loads from an object literal's instance field which is `final` (*really* `final`) can be replaced with a literal of the field's value.  This could result in the elimination of boot time objects. Also, it could help with inlining of method handles.

**Comment by dgrove-oss** [comment]
This seems like a fun one...if you haven't already started I can take a swing this week.

**Comment by dmlloyd** [comment]
Sounds good, go ahead.
