### ISSUE TITLE
`Class` objects as an array, revisited

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#1242]
We can eliminate a pointer indirection (`load`) when looking up a class object by type ID by holding all root class objects in a single array or contiguous piece of memory and using pointer arithmetic (`getelementptr`) to compute the pointer to the class object.  This takes advantage of the observations that root class objects can never be unloaded, are all considered GC roots, are of a uniform size, and are contiguous with no gaps (other than the gap for type ID `0`, though it could be argued that `void.class` should use this slot).

Contiguous placement of immovable class objects at the foot of the heap also allows this area of data to be parseable by GC in the exact same manner as other heap regions containing movable objects.

There are two possible approaches to doing this.

### Option 1: A single data object

This option is somewhat similar to what we have now. We create one `.ll` or other compilable source file containing the entire array of class objects, in order by type ID. The array may need to be emitted into a special section depending on GC needs.

This approach is the simplest in a lot of ways, however it means that one potentially huge source file would need to be compiled.

### Option 2: Class object in each object file

With this option, each class object is defined locally within the compilable source file (`.ll`) corresponding to that class as a single data object, assigned to the designated class objects section.  References to that particular class object from within the source file could optionally be done directly by address; otherwise the class object section base address would be considered the base of the class array, indexed by type ID.

This option requires that the object files corresponding to each class be linked in order by type ID - which is something we should be doing anyway to improve build reproducibility.

With this approach, compilation time should not be significantly impacted and we cut down on the number of giant source files we have.  A mistake in ordering of the class objects could potentially lead to hard-to-diagnose bugs, however it should be fairly straightforward to ensure that the files are linked in order and that no unexpected gaps appear in the class array.

Note that having `void.class` take slot zero would nicely allow the address of that class object to also double as the base pointer for the classes array, allowing LLVM GEP to access classes by ID via (for example) `%classp = getelementptr %class.java.lang.Class @void_class, %type_id`. An empty slot could be named for this purpose as well though, but with this approach that would require a special "first" object file to be linked before any other class.

**Comment by dgrove-oss** [comment]
Implemented Option 1 in #1265.
