### ISSUE TITLE
Compose initial heap from multiple input .ll files

### ISSUE THREAD

**Issue by dgrove-oss** [qbicc/qbicc#1245]
Related to (and inspired by) #1242.

We currently generate one massive .ll file that contains the entire initial heap (including all the String literals, Class objects, etc).  It might help llvm compilation time if we break this into multiple files (for example only a few thousand objects per file).  One complexity of doing this is that it means we can't assume that all the initial heap objects and types are in the same file, so we will have to more carefully manage cross-file declarations.

**Comment by dmlloyd** [comment]
Another possibility could be to put objects in the file corresponding to their class.

**Comment by dgrove-oss** [comment]
It takes 1.2 seconds for `llc` to process an InitialHeap.ll file with 60k objects and 1.7 seconds for `clang` to process the resulting `InitialHeap.s` file into `InitialHeap.o`.  We still might want to break the InitialHeap up to get more control over the memory layout, but reducing llvm compilation time doesn't look like a big concern.

**Comment by dgrove-oss** [comment]
#1265 implements the machinery to allow the InitialHeap to be split across multiple files, but only uses it to create two files.  One for the root class array and one for the rest of the heap.
