### ISSUE TITLE
String intern table population

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#1267]
We need a solution to bootstrap the interned string table at run time.  Right now we have separate concepts of build time interning, string serialization, and run time interning.  These concepts can and should be unified in a cohesive manner.

To bootstrap the string intern table at run time, there could be an initial heap object which is an array of all the strings to intern. A run time initializer in `java.lang.String` could take this array and populate the `INTERNED` map, and then discard the reference in such a way that the array can be collected.

To keep things simple, the array could (for example) be constructed of all of the strings that are reachable after lowering.

It might be worth enhancing the string intern table in `String$_native` to support both weak and strong references, since many build time strings (like those used in the method info tables) will always be strongly reachable. In this case we would probably want to have two arrays, with the appropriate machinery to ensure that each string only ends up in one of the two arrays.

**Comment by dgrove-oss** [comment]
Implemented a solution that makes build-time interned strings that actually make it into the initial heap strongly reachable and findable from a sorted root String[].  String.intern() uses binarySearch to first look for a build-time interned String and return it before creating a (weakly retained) entry in the runtime interned strings set.
