### ISSUE TITLE
Design: Create a Runtime Helpers API for use by generated code

### ISSUE THREAD

**Issue by DanHeidinga** [qbicc/qbicc#129]
As discussed in the Runtime Helpers Zulip thread [1], we need some helper calls for the generated code to call when the operation is too complicated to be compiled in at all occurrences - ie: instanceof/checkcast.

Things to think about:
* Calling convention for the generated code to call.  May be a private convention rather than C-call?
* Operations that require helpers (TODO: generate a list)
* Dealing with pending exceptions on return from the helper calls
* GC points inside the helpers
* Stack frames to ensure stack is walkable inside a helper if necessary
* Fast (no frame / no gc) and slow variants?

[1] = https://quarkusio.zulipchat.com/#narrow/stream/237892-qcc/topic/runtime.20helpers

**Comment by dmlloyd** [comment]
Can we call this essentially "done"? There would probably be some follow-ups but this is basically what we're doing now.

**Comment by DanHeidinga** [comment]
Agreed.  Closing
