### ISSUE TITLE
Aligning with JMM

### ISSUE THREAD

**Issue by michihirohorie** [qbicc/qbicc#152]
- We need to keep the JMM (Java Memory Model) to emit LLVM IR properly. Followings are TODO items.
    - [x] volatile read/write
        - Conservative approach is [LoadLoad/LoadStore/StoreLoad/StoreStore fences must be inserted properly before/after volatile read/write.](http://gee.cs.oswego.edu/dl/jmm/cookbook.html)
    - [x] final field
        - When a final field is initialized in a constructor, it must be visible to all threads just after the constructor ends.
        - https://docs.oracle.com/javase/specs/jls/se8/html/jls-17.html#jls-17.5
    - [x] class libraries 
        - VarHandle class has memory fence methods.
        - Unsafe class has some volatile related APIs. (Is Unsafe available in Quarkus?)
     - and more? (Maybe Java thread state visibility is out of the scope of JMM, which should be more related to the threading model, needed at GC safepoints etc.)
- Some optimizations step by step.
    - [ ] elimination of intra-procedural fence redundancy
    - [ ] elimination of inter-procedural fence redundancy 
    - [ ] some aggressive fence elimination based on global program analysis
    - If an application runs in a single thread, there is no necessity of memory fences.

**Comment by dmlloyd** [comment]
Per call, we'll call this complete. We can open separate issues to cover the various redundant fence eliminations.
