### ISSUE TITLE
Standardize the description of boolean[]

### ISSUE THREAD

**Issue by DanHeidinga** [qbicc/qbicc#409]
I think the correct thing to do is to track the type as a boolean array but lower it to a `u8` array.  Which means I'd need to change the Layout version.

Java's type system is a little weird as it knows that an array is of booleans but uses the byte load/store opcodes to operate on it

_Originally posted by @DanHeidinga in https://github.com/quarkuscc/qcc/pull/408#discussion_r590488886_

**Comment by dmlloyd** [comment]
I think this is fully solved by #493.
