### ISSUE TITLE
Process LLVM stack maps to produce method information table

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#475]
The stack maps which are produced by the LLVM stages must be processed and converted into a table format that can be consumed by the stack walker. The method information table format must be designed.

Add a hook to the `GENERATE` phase to perform this processing on each object file, and write the result to a new object file. One way to accomplish this would be to write an LLVM file comprising a single data item whose contents are the method information table as a complex literal, compile this file to an object file in the usual manner, and then add the resultant object file to the list of object files to be linked into the final image. The stack walker would refer to this table by symbol name.

Depends on #473 and #474.

**Comment by ashu-mehra** [comment]
Closed by https://github.com/qbicc/qbicc/pull/594
