### ISSUE TITLE
"Compiler terminated with exit code 1" for qbicc-integration-tests on macOS

### ISSUE THREAD

**Issue by rsvoboda** [qbicc/qbicc#527]
I'm getting "Compiler terminated with exit code 1" for qbicc-integration-tests on macOS.

I'm following steps described in https://github.com/qbicc/qbicc/issues/524#issuecomment-845935636

I'm using
```
$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/rsvoboda/.sdkman/candidates/maven/current
Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: /Users/rsvoboda/.sdkman/candidates/java/11.0.10.hs-adpt
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

$ sw_vers
ProductName:	macOS
ProductVersion:	11.3.1
BuildVersion:	20E241

$ llvm-config --version
12.0.0
```

Here is the build log - [qbicc.log](https://github.com/qbicc/qbicc/files/6539239/qbicc.log)

Any hints to provide more context are welcome. Just for the record, qbicc sits on default macOS volume, only qbicc-class-library sits on case sensitive volume.

**Comment by evacchi** [comment]
you may need to ensure that `/usr/local/lib/libgcc_s.dylib` exists

- simplest way for macOS Catalina and below, is adding a symlink in /usr/local/lib/libgcc_s.dylib pointing to /usr/lib/libgcc_s.1.dylib
- on Big Sur there is no /usr/lib/libgcc_s.1.dylib but a huge fat blob and the system files in dylibs as they are requested; long story short, you can't symlink this. instead `brew install gcc` and symlink `/usr/local/Cellar/gcc/11.1.0/lib/gcc/11/libgcc_s.1.dylib` (use whatever version of GCC you have installed there)

**Comment by rsvoboda** [comment]
Thanks, `ln -s /usr/local/Cellar/gcc/11.1.0/lib/gcc/11/libgcc_s.1.dylib /usr/local/lib/libgcc_s.dylib` helped. I'm on BigSur

**Comment by rsvoboda** [comment]
Should be https://github.com/qbicc/qbicc#requirements enhanced to cover the info from @evacchi or need for `libgcc_s.dylib` presence is something that will not be needed in the future?

**Comment by dmlloyd** [comment]
We will need some implementation of this API no matter what.  We might have to make the actual library be configurable though.  We don't want to depend on having LLVM, xcode, *and* gcc all installed on Mac.  So we might want to use a more general wording like "one way to get an implementation of this library is...", and list other methods as well if we can work them out.
