### ISSUE TITLE
Implement local variable debugging information

### ISSUE THREAD

**Issue by aviansie-ben** [qbicc/qbicc#539]
In order to allow for proper use of `gdb` and other debuggers to debug QBICC-generated executables, it will be necessary to output debug information to represent local variables and their values. Since we're using LLVM, this will require two things to be done:

1. Emit the correct `DILocalVariable` declarations representing the local variables in a method
2. Emit calls to `@llvm.dbg.addr` or `@llvm.dbg.value` to set the value/address of the local variable as needed

In terms of emitting the `DILocalVariable` declarations, there is one specific issue that needs to be addressed: scoping. LLVM represents scoping by using a tree of `DILexicalBlock` metadata nodes [1]. This means that we need to transform JVM bytecode's representation of local variable scopes as a list of bytecode ranges into a tree structure. These scopes should represent source-level order and _not_ actual execution order, so trying to generate them based off of IL seen by the LLVM codegen probably isn't a good idea. Each `DILocation` would then need to be assigned to the correct `DILexicalBlock` based on its bytecode index rather than the `DISubprogram` node.

The way I've done this in the past is by using an algorithm involving successively splitting, subdividing, and adding ranges to the tree of scopes and then adding each range seen in the JVM bytecode to the tree in turn. This may require splitting the live ranges of some variables into two separate live ranges to deal with any ranges that aren't well nested. I've put a generic implementation of the algorithm written in Rust at [2] for reference. I've also noticed that `javac` _seems_ to always generate well-nested ranges for its debug information, so it may be possible to use a simplified algorithm by assuming the ranges are well-nested and just erroring out if they're not. We might run into some future issues with this though, as I can't guarantee that `javac` will _always_ uphold this and I know that there definitely exist other generators of JVM bytecode that don't.

In terms of representing the value/address of the local variables, we would want to use LLVM's built-in intrinsics to do this. The easiest way to accomplish this would probably be to just add a couple new ordered node types that map to these intrinsics. Generally, using an `alloca` and `@llvm.dbg.addr` gives a better debugging experience, so that would probably be preferred for debug builds. Using `@llvm.dbg.value` can sometimes prevent the debugger from being able to change the value of a local variable at will since the value may be inlined into the instruction stream if it's a known constant, but allows optimizations to see through local variables, so that would be best used in optimized builds. I did this in a previous project by implementing a transformation pass that would go from one representation to the other using a simple dataflow analysis to transform loads/stores of local variables into SSA using phi nodes where appropriate and only running it in optimized builds. LLVM does actually support doing this already, but this transformation should be done early to allow QBICC's optimizer to see through these as well.

[1] https://llvm.org/docs/SourceLevelDebugging.html#object-lifetimes-and-scoping
[2] https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=64ab6d7b87e26199f63b413b95fd07dc

**Comment by dmlloyd** [comment]
This is all done except for the items listed in #578.
