### ISSUE TITLE
"Can't find the runtime helper method initialize_class" error in integration-tests on macOS

### ISSUE THREAD

**Issue by rsvoboda** [qbicc/qbicc#542]
Using qbicc main 78a2c946 I'm getting errors in integration-tests on macOS

```
2021-06-01 23:26:59.096 ERROR [o.q.t.i.u.QbiccDiagnosticLogger] (accept) error: Can't find the runtime helper method initialize_class

2021-06-01 23:26:59.096 ERROR [o.q.t.i.u.QbiccDiagnosticLogger] (accept) error: Pre-add hook failed: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 21
LoadedTypeDefinitionImpl.java:167: note: This is the location of the exception
    member: method getMethod
  location: type LoadedTypeDefinitionImpl
```

This failure is most likely related to https://github.com/qbicc/qbicc/pull/530

I had successful run when using b37cdca0 (14 days old commit)

Tests failed for me when using 26206ad4ebb1d07d960b915b6d8a3c927c2f6dc8 (1 week old commit, but contains 13 days old commits from mentioned PR)

**Comment by dmlloyd** [comment]
You might need a clean rebuild. That is sometimes the case when methods are added/removed/changed in the runtime library because they're not always strictly considered dependencies in some cases (they're used by the integration tests but not by the compilation process) so sometimes in-IDE testing fails when this happens.

**Comment by rsvoboda** [comment]
I executed `mvn clean verify` against main / b37cdca / 26206ad and only b37cdca worked for me.

**Comment by rsvoboda** [comment]
You were right @dmlloyd, after running `mvn clean install -DskipTests` tests are passing again.
