### ISSUE TITLE
Array dimensions field should be unsigned byte

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#581]
The array dimensions field should be an unsigned byte.  The corresponding `VMHelpers` methods would have to be modified to accept a `uint8_t`, which in turn changes their signature for the purposes of lookup.

**Comment by evacchi** [comment]
If I understand correctly, the change starts here:

https://github.com/qbicc/qbicc/blob/3362d8f1720ada7f12e5f38f3a3a58e48c94fac9/plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/CoreClasses.java#L188-L199

and cascades from there, is that right?

`type` must first of all be set to `uint8_t`. I assume this also means that `BaseTypeDescriptor`, `BaseTypeSignature` should be `B`s

**Comment by dmlloyd** [comment]
It's deceptive; for C types, they have the descriptor of the corresponding Java class so the descriptor would not be `B`, it would be `Lorg/qbicc/runtime/CNative$uint8_t` (iirc).

**Comment by dmlloyd** [comment]
But note that using `fieldBuilder.setType` prevents the descriptor from being used for type resolution (which is why you sometimes see a field with a descriptor type of `void` - pure laziness 😉)
