### ISSUE TITLE
`VariableElement`s should have alignment

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#582]
It should be possible to specify a minimum alignment for `VariableElement`s.  The final alignment would be the maximum of the element's minimum alignment (as given in the element builder) and the type's minimum alignment.

The alignment information would then be used by `Layout` and the various allocators.

**Comment by dgrove-oss** [comment]
I believe this was done by https://github.com/qbicc/qbicc/pull/1647
