### ISSUE TITLE
Add startMethod for capturing method entry

### ISSUE THREAD

**Issue by galderz** [qbicc/qbicc#591]
Add a `startMethod` call, symmetrical to `finish`, that captures the method entry invocation. This can be useful for optimisations such as escape analysis, that summarise methods independent of the call sites.

Right now the closest you can get is to catch `begin` and keep a flag to see if it's the first block.

**Comment by dmlloyd** [comment]
It would be nice if `startMethod` accepted all of the method parameters as `List<Value>` as well.
