### ISSUE TITLE
IllegalStateException: Cannot reach previously unreachable element

### ISSUE THREAD

**Issue by michihirohorie** [qbicc/qbicc#636]
I hit `IllegalStateException: Cannot reach previously unreachable element` due to [in RTAInfo](https://github.com/qbicc/qbicc/blob/main/plugins/reachability/src/main/java/org/qbicc/plugin/reachability/RTAInfo.java#L381).

Root cause seems to be `Object.toString()` is overwritten as native [in qbicc-class-library](https://github.com/qbicc/qbicc-class-library/blob/main/java.base/src/main/java/java/lang/Object.java#L51).
I’m wondering if we can use the original `Object.toString()`, although I don’t know the background discussions on the `Object` overwrite  necessity. With the original `Object.toString()`, this Exception does not occur.

For what I observed to reach the Exception

At the ADD phase
1. RuntimeCheckBasicBlockBuilder throws BlockEarlyTermination for the invocations to `Object.toString()`.
https://github.com/qbicc/qbicc/blob/main/plugins/correctness/src/main/java/org/qbicc/plugin/correctness/RuntimeChecksBasicBlockBuilder.java#L289-L293
2. RTAInfo does not enqueue `toString()` of `A` class whose super class is `Object` because `Object.toString()` is not regarded as the invokable method yet. `isInvokableMethod(overiddenMethod)` returns `false`.
https://github.com/qbicc/qbicc/blob/main/plugins/reachability/src/main/java/org/qbicc/plugin/reachability/RTAInfo.java#L378
3. RTAInfo enqueues `Object.toString()` after a while. 
https://github.com/qbicc/qbicc/blob/main/plugins/reachability/src/main/java/org/qbicc/plugin/reachability/RTAInfo.java#L396

At the ANALYZE phase

  4.  RTAInfo enqueues `Object.toString()`.
https://github.com/qbicc/qbicc/blob/main/plugins/reachability/src/main/java/org/qbicc/plugin/reachability/RTAInfo.java#L396
5. RTAInfo enqueues `toString()` of `A` class whose super class is `Object` because `Object.toString()` is already invokable due to step4. `isInvokableMethod(overiddenMethod)` returns `true`.
https://github.com/qbicc/qbicc/blob/main/plugins/reachability/src/main/java/org/qbicc/plugin/reachability/RTAInfo.java#L381
6. `IllegalStateException: Cannot reach previously unreachable element` occurs on `A.toString()`.

I don’t still understand why step4 (enqueuing `Object.toString()`) happens before step5 at the ANALYZE phase, even though step3 (enqueuing `Object.toString()`) happened after step2 at the ADD phase.

This situation seems to come from the BlockEarlyTermination for `Object.toString()`. When I use the original non-native `Object.toString()`, the order of step2 and step3 is kept as is at the ANALYZE phase (thus, the order becomes step5 then step4. `A.toString` is enqueued  because `Object.toString()` was already enqueued at the beginning of the ANALYZE phase without BlockEearlyTermination.). 

This situation happens even in a single thread compilation. 

I’ve being trying to reproduce the same problem in a small code to share with everyone, but not succeeded in doing it. Hitting this Exception closely relates to the order of enqueuing methods in RTAInfo and the problem happens in the Java library side, which may be tricky to reproduce ...

**Comment by dgrove-oss** [comment]
Not 100% positive on the history, but I suspect that the default non-native `toString`
```
    public String toString() {
        return getClass().getName() + "@" + Integer.toHexString(hashCode());
    }
```
pulls in more of the JDK than was desired at the time.  This code still won't actually work if a program  tries to execute it, but maybe we could restore it now without actually increasing how much of the JDK we pull in.

If that isn't viable, then we should probably add a stub implementation of toString to `CoreIntrinsics.registerJavaLangObjectIntrinsics` to avoid needing a special case in RTA.

**Comment by michihirohorie** [comment]
OK. I added `toString` to `CoreIntrinsics.registerJavaLangObjectIntrinsics`, but the Exception still occurs with the same reason. Currently, the intrinsic only returns a StringLiteral.

I’ll continue to look into this problem.

**Comment by dgrove-oss** [comment]
I think there's a good chance #640 will fix this.  If not, let me know.

**Comment by michihirohorie** [comment]
I confirmed #640 fixes this problem even if `Object.toString` is declared as native. Thanks.
Since `Object.toString` is now restored to non-native, I close this issue anyway.
