### ISSUE TITLE
Properly implement `Unsafe.unalignedAccess0`

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#651]
Right now the intrinsic for `unalignedAccess0` introduced in #650 pessimistically returns `false` for all platforms. We need either a way to probe for this fact via a C probe, or else to hard code in the list of CPUs whether that particular target supports unaligned accesses (or maybe even make it switchable, as it's possible that some platforms may sometimes allow it and sometimes not at the option of the OS or even the chip implementation).

**Comment by dmlloyd** [comment]
Another aspect of this problem is understanding what exactly this value indicates. For example, we could generate unaligned loads to LLVM on all platforms and [it will "make it work"](https://llvm.org/docs/LangRef.html#id207), albeit at a performance cost on some platforms. Unaligned accesses are almost certainly slower than aligned accesses even on CPUs which support them, particularly if the access crosses a word boundary. So it is possible that we could successfully return the constant `true` here, relying on LLVM to sort out the gnarly details. The only caveat I can think of is that the interpreter does not under any circumstances allow unaligned loads/stores of references or pointers.

**Comment by DanHeidinga** [comment]
The primary use I know if is in things like NIO to determine if more optimized writes - like writing a full int/long at a time - are possible or if the platform needs to write byte-by-byte.

The apis asking for aligned or unaligned access only support primitive types - Java doesn't allow users to write object pointers into off-heap memory as they are immediate corrupt at that point so I don't think we need to worry about references.

**Comment by dmlloyd** [comment]
I guess then it comes down to the question of whether the NIO unaligned read/write utilities are faster or slower than LLVM's unaligned reads/writes. Or, on the other side of the coin, whether our generated IR code for the NIO utilities is tight enough that LLVM recognizes any unaligned reads/writes and turns them back into single instructions (it has this capability but might expect a specific code shape for it).

**Comment by DanHeidinga** [comment]
> Or, on the other side of the coin, whether our generated IR code for the NIO utilities is tight enough that LLVM recognizes any unaligned reads/writes and turns them back into single instructions (it has this capability but might expect a specific code shape for it).

I think it will depend on the levels of inlining we get.  The unaligned OK case is s single method call while the other case is multiple calls to write a byte each.

**Comment by dgrove-oss** [comment]
JDK 17 got rid of the native methods for unalignedAccess, addressSize, and endianness.  We are now doing something more precise in UnsafeConstants$_patch.
