### ISSUE TITLE
`ArrayLength`, `TypeIdOf`, and `CurrentThreadRead` are actually all `Load` ops

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#697]
These three `Value` types are actually load operations that don't use the `Load` node.  In the interests of keeping memory accesses largely unified, I suggest the following:

- [x] #783
- [x] #789
- [x] #844

Update, I'm adding a fourth one.

- [x] #858

**Comment by dgrove-oss** [comment]
#783 #789 and $784 completed.  After further analysis, we decided #858 is a won't do.
