### ISSUE TITLE
Reachability performance enhancement

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#751]
One way we could improve reachability analysis would be to change the algorithm to not process the program graph of each element until `finish()`, when the graph is fully constructed.  This way, unreachable parts of the graph will already have been pruned, potentially avoiding a significant amount of redundant work (since constant conditions in `If`s will have been converted to `Goto`).

The analyzer would necessarily use a visitor and track a visited-set.  See `org.qbicc.type.definition.classfile.MethodParser.PhiPopulator` for an example of how this can be done in a fairly minimal form.

**Comment by dgrove-oss** [comment]
> A (really sloppy) test indicates that this could easily reduce the final class count by over 100.

ok, that's interesting.  Do you have something in flight already or is this something I should look at this week?

**Comment by dmlloyd** [comment]
I have nothing worth sharing! Go ahead if you want to.
