### ISSUE TITLE
ClassOf should be a ValueHandle

### ISSUE THREAD

**Issue by dgrove-oss** [qbicc/qbicc#858]

**Comment by dgrove-oss** [comment]
For the base case (where the dimensions are 0), it is reasonable to have `ClassOf` be a `ValueHandle`.  There's a straightforward translation to a `ElementOf(GlobalVariable(classArray), typeId)`.  However, when dimensions is non-zero, the code is more interesting...we need to invoke a runtime helper method that loops through n-1 iterations of loading (and lazily creating if necessary) the `java.lang.Class` object for the array type from the `Class` object of the element type.  This method is used in several places, and most naturally should return a `java.lang.Class` instance. 

It seems doable to have `ClassOf(typeId)` value handle to use in the majority of the cases where we know at compile time the dimensions is 0.  The other case would get directly expanded to a `Call` of `ObjectModel.get_class_from_type_id(typeId, dimensions)`.

Does this make sense?

**Comment by dgrove-oss** [comment]
It's a bit annoying, since if we restrict the `ClassOf` to only cover those cases with dimension of zero (ie, those cases where it is going to really be a handle), then we end up bifurcating the handling of class literals in `MethodParser.getConstantValue`.  

After poking at this a bit more,  I'm not sure it really makes sense to do this conversion because of the dimensions>0 aspect of the existing `ClassOf` node.

**Comment by dmlloyd** [comment]
I agree with your analysis.

**Comment by dgrove-oss** [comment]
Closing as won't fix.
