### ISSUE TITLE
Object replacement on serialize/deserialize

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#940]
We will soon need a solution for replacement of serialized heap objects.  I believe the instigating use case will be `FileDescriptor`.  We might be able to get by with a solution here which replaces all `FileDescriptor` instances with one single closed (i.e. `fd == -1`, `closed == true`, no `Closeable` values) instance.

**Comment by dgrove-oss** [comment]
Handled by adding @SerializeAs annotations in #1027 and finishing patcher support for annotations in #1076.
