### ISSUE TITLE
Catalog initialization steps by OS

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#950]
In order to work out a cogent JVM initialization and re-initialization process, we have to analyze the steps performed by OpenJDK today.

These steps must be assembled from multiple places. They could be organized into two broad categories: cross-platform and platform-specific.

The majority of the cross-platform steps can be found by reading `System.initPhase1`,`initPhase2`, and `initPhase3`, with the "glue" in between these steps being found in `openjdk/src/hotspot/share/runtime/thread.cpp`.  In between these steps, platform-specific initialization occurs.  This can be understood by reading the `Threads::create_vm` method in `thread.cpp`, and following the OS-specific calls (e.g. `os::init()`, `os::init_before_ergo()`, `os::pause()`, etc.).

These steps should be charted out into a table.  For each table row, the applicable OS(es) should be denoted, as well as at least a guess at whether the step (or an equivalent step) should be performed at build time, run time, or both.

**Comment by dmlloyd** [comment]
Example format:

<table>
<tr><th>BT?<th>RT?<th>Description<th>Phase<th>Found in
<tr><td>Y<td><td>`setJavaLangAccess`<td>1<td>`System.initPhase1()`
</table>

**Comment by dgrove-oss** [comment]
I've made an initial cut in the wiki: https://github.com/qbicc/qbicc/wiki/Qbicc-Initialization-Steps

**Comment by dmlloyd** [comment]
Initialization is fully functional now.
